apiVersion: v1
kind: ConfigMap
metadata:
  name: cbass-config
data:
  PORT: "3000"
  NAME: "cbass"
  JWT_SECRET: "${JWT_SECRET}"
  SHARED_DB_URI: "${SHARED_DB_URI}"
  TENANT_DB_PREFIX: "${TENANT_DB_PREFIX}"
  AUTH_VERIFY_URL: "${AUTH_VERIFY_URL}"