apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  ports:
  - name: http        # <── required by Istio / Kiali
    port: 80
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: account
spec:
  selector:
    app: account
  ports:
  - name: http
    port: 80
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: transaction
spec:
  selector:
    app: transaction
  ports:
  - name: http
    port: 80
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: usage
spec:
  selector:
    app: usage
  ports:
  - name: http
    port: 80
    targetPort: 3000
