apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  ports:
  - port: 80
    targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: account
spec:
  selector:
    app: account
  ports:
  - port: 80
    targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: transaction
spec:
  selector:
    app: transaction
  ports:
  - port: 80
    targetPort: 3000
