name: CI/CD to Huawei SWR and CCE

on:
  push:
    branches:
      - main

env:
  REGION: af-south-1
  REGISTRY: swr.af-south-1.myhuaweicloud.com/ralf

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Huawei Cloud SWR
        uses: huaweicloud/swr-login@v2.1.0
        with:
          access-key-id: ${{ secrets.ACCESSKEY }}
          access-key-secret: ${{ secrets.SECRETACCESSKEY }}
          region: af-south-1

      - name: Build and push Docker images
        run: |
          docker build -t $REGISTRY/auth:${{ github.sha }} ./auth-service
          docker push $REGISTRY/auth:${{ github.sha }}

          docker build -t $REGISTRY/account:${{ github.sha }} ./account-service
          docker push $REGISTRY/account:${{ github.sha }}

          docker build -t $REGISTRY/transaction:${{ github.sha }} ./transaction-service
          docker push $REGISTRY/transaction:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" > $HOME/.kube/config


      - name: Update image versions in deployments
        run: |
          sed -i "s|auth-image|swr.af-south-1.myhuaweicloud.com/ralf/auth:${{ github.sha }}|g" k8s/deployment.yaml
          sed -i "s|account-image|swr.af-south-1.myhuaweicloud.com/ralf/account:${{ github.sha }}|g" k8s/deployment.yaml
          sed -i "s|transaction-image|swr.af-south-1.myhuaweicloud.com/ralf/transaction:${{ github.sha }}|g" k8s/deployment.yaml

      - name: Apply ConfigMap to CCE
        run: |
          kubectl apply -f - <<EOF
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: cbass-config
          data:
            PORT: "3000"
            NAME: "cbass"
            JWT_SECRET: "${{ secrets.JWT_SECRET }}"
            SHARED_DB_URI: "${{ secrets.SHARED_DB_URI }}"
            TENANT_DB_PREFIX: "${{ secrets.TENANT_DB_PREFIX }}"
            AUTH_VERIFY_URL: "${{ secrets.AUTH_VERIFY_URL }}"
            KAFKA_BROKERS: "${{ secrets.KAFKA_BROKERS }}"
            KAFKA_TOPIC: "${{ secrets.KAFKA_TOPIC }}"
            PG_HOST: "${{ secrets.PG_HOST }}"
            PG_PORT: "${{ secrets.PG_PORT }}"
            PG_USER: "${{ secrets.PG_USER }}"
            PG_PASSWORD: "${{ secrets.PG_PASSWORD }}"
            PG_DATABASE: "${{ secrets.PG_DATABASE }}"
          EOF



      - name: Apply K8s manifests to CCE
        run: |
          kubectl apply -f k8s/


  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install Dependencies
        run: cd frontend && npm ci

      - name: Build Frontend
        run: cd frontend && npm run build

      - name: Upload to Huawei OBS
        uses: lemrex/Sync-OBS@v1.0.0
        with:
          accessKey: ${{ secrets.ACCESSKEY }}
          secretKey: ${{ secrets.SECRETACCESSKEY }}
          region: af-south-1
          obsBucket: vuejs
          localPath: frontend/build/

  build-analytics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: analytics/package-lock.json


      - name: Install Dependencies
        run: cd frontend && npm ci

      - name: Build Frontend
        run: cd frontend && npm run build

      - name: list directory
        run: ls -la analytics

      - name: list directory2
        run: ls ./     

      - name: Upload to Huawei OBS
        uses: lemrex/Sync-OBS@v1.0.0
        with:
          accessKey: ${{ secrets.ACCESSKEY }}
          secretKey: ${{ secrets.SECRETACCESSKEY }}
          region: af-south-1
          obsBucket: vuejs
          localPath: analytics/out/


