name: CI/CD to Huawei SWR and CCE

on:
  push:
    branches:
      - main

env:
  REGION: af-south-1
  REGISTRY: swr.af-south-1.myhuaweicloud.com/ralf

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Huawei Cloud SWR
        uses: huaweicloud/swr-login@v2.1.0
        with:
          access-key-id: ${{ secrets.ACCESSKEY }}
          access-key-secret: ${{ secrets.SECRETACCESSKEY }}
          region: af-south-1

      - name: Build and push Docker images
        run: |
          docker build -t $REGISTRY/auth:${{ github.sha }} ./auth-service
          docker push $REGISTRY/auth:${{ github.sha }}

          docker build -t $REGISTRY/account:${{ github.sha }} ./account-service
          docker push $REGISTRY/account:${{ github.sha }}

          docker build -t $REGISTRY/transaction:${{ github.sha }} ./transaction-service
          docker push $REGISTRY/transaction:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" > $HOME/.kube/config


      - name: Update image versions in deployments
        run: |
          sed -i "s|auth-image|swr.af-south-1.myhuaweicloud.com/ralf/auth:${{ github.sha }}|g" k8s/deployment.yaml
          sed -i "s|account-image|swr.af-south-1.myhuaweicloud.com/ralf/account:${{ github.sha }}|g" k8s/deployment.yaml
          sed -i "s|transaction-image|swr.af-south-1.myhuaweicloud.com/ralf/transaction:${{ github.sha }}|g" k8s/deployment.yaml

      - name: Apply ConfigMap to CCE
        run: |
          kubectl apply -f - <<EOF
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: cbass-config
          data:
            PORT: "3000"
            NAME: "cbass"
            JWT_SECRET: "${{ secrets.JWT_SECRET }}"
            SHARED_DB_URI: "${{ secrets.SHARED_DB_URI }}"
            TENANT_DB_PREFIX: "${{ secrets.TENANT_DB_PREFIX }}"
            AUTH_VERIFY_URL: "${{ secrets.AUTH_VERIFY_URL }}"
          EOF



      - name: Apply K8s manifests to CCE
        run: |
          kubectl apply -f k8s/



          